#!/usr/bin/env python

import rospy
from egh450_navigation_interface.navigation_interface import NavigationInterface

if __name__ == '__main__':
	# Initialize
	rospy.init_node('egh450_navigation_interface', anonymous=True)
	
	nav = None
	
	try:
		nav = NavigationInterface()
	
		rospy.loginfo("[NAV] Navigator node running")

		# Loop here until quit
		rospy.spin()
	except rospy.ROSInterruptException:
		rospy.loginfo("[NAV] Navigator shutting down")
	finally:
		# Shutdown if nav was started successfully
		if nav is not None:
			nav.shutdown()
